apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: jenkins
          image: tousi/jenkins-docker-maven:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-persistent-storage
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: jenkins-persistent-storage
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: ci-cd
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31801
      targetPort: 8080
  selector:
    app: jenkins

